allowBuilds:
  unrs-resolver: false

autoInstallPeers: false

minimumReleaseAge: 720

minimumReleaseAgeExclude:
  - "@codemod-utils/*"
  - "@ijlee2-frontend-configs/*"

resolvePeersFromWorkspaceRoot: false
